-- 게시판 테이블 생성
CREATE TABLE PT_BOARD (
	 PT_WEL	 VARCHAR2(4000) NULL,
	 PT_DIET VARCHAR2(2000)	NULL,
	 PT_EXE VARCHAR2(2000) 	NULL,
	 PT_QNA	VARCHAR2(4000)	NULL,
	 PT_BFAF	VARCHAR2(2000)	NULL
);

SELECT PT_WEL 가입인사, PT_DIET "오늘의 식단", PT_EXE "오늘의 운동",
			  PT_QNA 질문과답변, PT_BFAF "전/후사진"
FROM PT_BOARD;

-----------------------------------------------------

-- 회원정보 테이블 생성
CREATE TABLE PT_MEMBER(
		MEM_NO NUMBER NOT NULL,
		MEM_NAME VARCHAR2(30) NOT NULL,
		MEM_SSN VARCHAR2(30) NOT NULL,
		MEM_HEIGHT NUMBER NOT NULL,
		MEM_WEIGHT NUMBER NOT NULL,
		MEM_INFAT NUMBER NOT NULL,
		PRIMARY KEY(MEM_NO)
);

-- 컬럼 자료형 변경
--ALTER TABLE PT_MEMBER MODIFY MEM_SSN VARCHAR2(30); 

-- MEM_NO 시퀀스 설정
CREATE SEQUENCE SEQ_MEM_NO
INCREMENT BY 1 
START WITH 1 
MINVALUE 1
MAXVALUE 1000 
NOCYCLE
NOCACHE; 

SELECT * FROM PT_MEMBER;

-- 회원정보 테이블에 데이터 삽입
INSERT INTO PT_MEMBER(MEM_NO, MEM_NAME, MEM_SSN, 
						MEM_HEIGHT, MEM_WEIGHT, MEM_INFAT)
VALUES('01', '김정은', '800905-1000001', '110', '160', '40');
INSERT INTO PT_MEMBER
VALUES('02', '전창대', '961102-1000002', '82', '175', '28');
INSERT INTO PT_MEMBER
VALUES('03', '강나은', '940830-2000003', '50', '164', '20');
INSERT INTO PT_MEMBER
VALUES('04', '백장미', '970327-2000004', '45', '156', '22');
INSERT INTO PT_MEMBER
VALUES('05', '배근원', '881214-1000005', '76', '172', '21');

COMMIT;

-- 아래 소스 설명하면, DBMS_RANDOM 을 통해 난수 발생시키고(1~1000), 
-- 난수 값을 round (반올림) 한 것을 TEST 에 INSERT 한다. 위 행위를 5번 반복한다.
INSERT INTO PT_MEMBER
SELECT  ROUND(DBMS_RANDOM.vALUE(6, 50), 0),
               ROUND(DBMS_RANDOM.vALUE(NULL),
               ROUND(DBMS_RANDOM.vALUE(1, 1000), 0),
               ROUND(DBMS_RANDOM.vALUE(1, 1000), 0),
               ROUND(DBMS_RANDOM.vALUE(1, 1000), 0),
               ROUND(DBMS_RANDOM.vALUE(1, 1000), 0)
FROM dual
CONNECT BY LEVEL <= 5;


SELECT * FROM PT_MEMBER;
ROLLBACK;


-----------------------------------------------------

-- 회원별 체중/체지방 기록 테이블 생성
CREATE TABLE BMI_DATA(
		BMI_NO NUMBER NOT NULL,
		BMI_WEIGHT NUMBER NOT NULL,
		BMI_DATE DATE DEFAULT SYSDATE,
		MEM_NUM NUMBER REFERENCES PT_MEMBER(MEM_NO)
);

-- BMI_NO 시퀀스 설정
CREATE SEQUENCE SEQ_BMI_NO
INCREMENT BY 1 
START WITH 1 
MINVALUE 1
MAXVALUE 1000 
NOCYCLE
NOCACHE; 

-- BMI_WEIGHT 시퀀스 설정
CREATE SEQUENCE SEQ_BMI_WEIGHT
INCREMENT BY 1 
START WITH 1 
MINVALUE 1
MAXVALUE 1000 
NOCYCLE
NOCACHE; 

SELECT * FROM BMI_DATA


-----------------------------------------------------







